### ISSUE TITLE
Libusb error with canable gs_usb device

### ISSUE THREAD

**Issue by prunith** [jxltom/gs_usb#13]
When run exmple with canable device it fail with error:

`Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    dev.start()
  File "C:\Users\100034799\AppData\Local\Programs\Python\Python310-32\lib\site-packages\gs_usb\gs_usb.py", line 66, in start
    self.gs_usb.ctrl_transfer(0x41, _GS_USB_BREQ_MODE, 0, 0, mode.pack())
  File "C:\Users\100034799\AppData\Local\Programs\Python\Python310-32\lib\site-packages\usb\core.py", line 1071, in ctrl_transfer
    self._ctx.managed_open()
  File "C:\Users\100034799\AppData\Local\Programs\Python\Python310-32\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\100034799\AppData\Local\Programs\Python\Python310-32\lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\100034799\AppData\Local\Programs\Python\Python310-32\lib\site-packages\usb\backend\libusb0.py", line 501, in open_device
    return _check(_lib.usb_open(dev))
  File "C:\Users\100034799\AppData\Local\Programs\Python\Python310-32\lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [os_open] failed to open \\\\.\\libusb0-0003--0x1d50-0x606f: win error: Le fichier sp\xe9cifi\xe9 est introuvable.\r\n'`

configuration detail:
Python 3.10
Windows 10
usb driver: libusb-win32 (v1.2.7.3)
canable FW : [candleLight_gsusb](https://github.com/candle-usb/candleLight_fw#candlelight_gsusb)

**Comment by karthik-argo** [comment]
I have the same issue. Did you find a solution?
